name: 'Action Agogo!'
description: 'Trying out container-based actions -- do not use!'
author: 'Joshua M. Clulow <josh@sysmgr.org>'
inputs: 
  colour:
    description: 'What colour should it be?'
    default: 'green'
  secret:
    description: 'Access token for buildomat service?'
    required: true
runs:
  using: 'docker'
  image: 'docker://jclulow/buildomat:latest'
  args:
    - ${{ inputs.colour }}
  env:
    WHOM: 'THEE!'
    COLOUR_ENV: ${{ inputs.colour }}
    SECRET: ${{ inputs.secret }}
