name: 'Action Agogo!'
description: 'Trying out container-based actions -- do not use!'
author: 'Joshua M. Clulow <josh@sysmgr.org>'
inputs: 
  script:
    description: 'bash script to run in the guest'
    required: true
  baseurl:
    description: 'base URL for buildomat service'
    required: true
  secret:
    description: 'access token for buildomat service'
    required: true
runs:
  using: 'docker'
  image: 'docker://jclulow/buildomat:latest'
